# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a107e40065cf364616be4e0d91e316cac1571268f0e0391ac6436fa6d3c79ac663760ae4cf76aec809be04dffd915e983eb141c91bda05c5549d700446cd31

test:
  secret_key_base: c02ffb2a5cfc301c63d55734a846ed31e234dce04b23f494abfd95e8b7c0faa6a853c6d4dcffff8630f7dfb65bc2d4ae40fe818ecc307618a9e2c62834db482d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
